### ISSUE TITLE
Getting an error on program startup + White window after clicking 'schedule'

### ISSUE THREAD

**Issue by DoctorMichaelMorbius** [shopgoodwill-sniper/shopgoodwill-auction-sniper#61]
✓On the latest version
✓Ran with Powershell as administrator

Upon program startup:
![image](https://github.com/user-attachments/assets/abad9421-62f2-44e0-92a3-f4e0dbca27a2)

After I hit okay on the above error, it takes me into the program normally where I can login and browse the site normally, however once I enter the item number and minimum bid (also tried it with no maximum bid) and click schedule, a second window opens but it's just a blank white screen, and even after waiting for a long time nothing shows up:

After clicking 'schedule':
![image](https://github.com/user-attachments/assets/d94bb13e-b566-4c89-bf2a-b817c11d35fa)

**Comment by shopgoodwill-sniper** [comment]
Hi DoctorMichaelMorbius,

Thank you for reporting this issue to us, it seems there was an issue with our last release update in compilation that was causing the error, furthermore, the issue has been resolved, you can download the new fixed version off our website at Snipeable.com by running the install/update command again, this time it will work perfectly for you!

Please let us know if we can be of further assistance.

Best regards,
Technical Support
Snipeable.com

**Comment by DoctorMichaelMorbius** [comment]
Unfortunately it still isn't working after updating, I also received this error after running the update command: 
![image](https://github.com/user-attachments/assets/11bdd355-794b-4d70-935e-d7fea959603e)

**Comment by shopgoodwill-sniper** [comment]
It is working we just tested it, it's your computer this time, restart your computer run the command again it should work.

**Comment by DoctorMichaelMorbius** [comment]
Alright thank you, also the Mac version doesn't seem to open

**Comment by shopgoodwill-sniper** [comment]
Everything works Dr Michael Morbius if you come here and you complain one more time I will block you from even being able to return or use our software! So take your ahhh off our website and stop blaming your cheap computer issues on us, now GTFOH!!!

**Comment by DoctorMichaelMorbius** [comment]
Why are you being hostile? I reported one issue and I was right lol.

**Comment by shopgoodwill-sniper** [comment]
No, you're just complaining and nagging and wasting my $150 per hour time and if you say one more thing I'll block you completely from using our software at all.

**Comment by craigrileyuk** [comment]
> No, you're just complaining and nagging and wasting my $150 per hour time

Your README says you're $25 an hour...
